-- =====================================================================
-- GeoSphere 360 — Persist the survey metadata filename set (Migration 0034)
--
-- WHY THIS TABLE IS NEEDED
--
-- Migration 0029 gave `staging_panoramas` a `csv_file_name` column, but that
-- stores the CSV's NAME — `20260925.csv` — and not its rows. Nothing in the
-- schema retains which images the survey metadata actually declared.
--
-- That makes three of the ten figures in the Data Management integrity panel
-- impossible to compute for a stored run:
--
--   Duplicate          — the same image recorded more than once
--   Invalid filename   — a recorded name that is not a usable frame name
--   Metadata mismatch  — metadata naming a different image than the run did
--
-- All three existed only at CSV import time, held in React component state,
-- and were discarded when the import dialog closed
-- (`DataManagementPage.tsx:1430-1433`). Duplicate detection was never
-- available for a run already in the database.
--
-- This table stores the filename set per run so the figures are permanent and
-- recomputable, for both staged and published runs.
--
-- WHY IT IS A TABLE AND NOT A COLUMN
--
-- A CSV holds hundreds of thousands of rows. They cannot live in a column, and
-- reconstructing them later requires the NAS to be reachable — which makes
-- historical comparison an operation with a runtime dependency rather than a
-- query. Persisting at import time is the only moment the rows are in hand.
--
-- SCOPE AND HONEST LIMIT
--
-- Forward-only. Runs imported before this migration have no set, and their
-- three rows read "not captured at import" rather than 0. Backfilling would
-- require the NAS, which is an operation and not a migration. This is stated in
-- the panel rather than papered over, because a 0 here would read as "we
-- checked and found nothing wrong".
--
-- Safe to re-run.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. The table
-- ---------------------------------------------------------------------
create table if not exists public.survey_metadata_filenames (
    id            bigint generated by default as identity primary key,
    project_id    uuid not null references auth.users(id) on delete cascade,
    subgrid       text not null,
    run_id        text,
    csv_file_name text,
    filename      text not null,
    created_at    timestamptz not null default now(),

    -- One row per (project, subgrid, run, filename). The writer upserts in bulk
    -- per imported run, so this is what makes a re-import idempotent rather than
    -- accumulating duplicates — which is the very condition the Duplicate row
    -- is meant to measure.
    constraint survey_metadata_filenames_unique
        unique (project_id, subgrid, run_id, filename)
);

comment on table public.survey_metadata_filenames is
    'Filenames declared by the survey metadata CSV for one run. Persisted at import time so duplicate, invalid-name and metadata-mismatch figures are recomputable for a stored run. Empty for runs imported before migration 0034.';

comment on column public.survey_metadata_filenames.run_id is
    'Run identifier this metadata row belongs to (sp-d-<runKey> or staging-d-<runKey>). NULL groups rows imported before a run existed.';

-- ---------------------------------------------------------------------
-- 2. Indexes
-- ---------------------------------------------------------------------
-- The panel reads every filename for one run; without this it degrades to a
-- sequential scan of the whole project on each row the operator clicks.
create index if not exists idx_survey_metadata_filenames_run
    on public.survey_metadata_filenames (project_id, subgrid, run_id);

-- ---------------------------------------------------------------------
-- 3. Row Level Security
--
-- Same shape as file_inventory (0006/0028) and the application tables:
-- every policy is role-guarded through sec.can, so authorization lives in the
-- database rather than in the interface.
-- ---------------------------------------------------------------------
alter table public.survey_metadata_filenames enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename  = 'survey_metadata_filenames'
       and policyname = 'survey_metadata_filenames_select'
  ) then
    create policy survey_metadata_filenames_select
        on public.survey_metadata_filenames
        for select
        to authenticated
        using (sec.can('viewAll') or project_id = auth.uid());
  end if;

  -- Writes require import rights. A Viewer can read a run's completeness but
  -- cannot assert one.
  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename  = 'survey_metadata_filenames'
       and policyname = 'survey_metadata_filenames_insert'
  ) then
    create policy survey_metadata_filenames_insert
        on public.survey_metadata_filenames
        for insert
        to authenticated
        with check (sec.can('editData') and project_id = auth.uid());
  end if;
end $$;

revoke all on table public.survey_metadata_filenames from anon;

COMMIT;

-- NOTE: PostgREST caches the schema. After running this, reload it with
--   NOTIFY pgrst, 'reload schema';
-- or restart the PostgREST container, otherwise selects against
-- `survey_metadata_filenames` fail with PGRST204 until the cache is refreshed.